application:
  host: 0.0.0.0
  # base_url: env value from APP_APPLICATION__BASE_URL
database:
  host: host.docker.internal
  require_ssl: false
email_client:
  base_url: "https://api.postmarkapp.com"
  sender_email: "dk.kam@tg360tech.com"